apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  resources:
    - name: source
      type: git
    - name: image
      type: image
  tasks:
    - name: build
      taskRef:
        name: golang-source
