apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: deploy-pipeline-run
spec:
  pipelineRef:
    name: deploy-pipeline
  resources:
    - name: source
      resourceSpec:
        type: git
        params:
          - name: revision
            value: master
          - name: url
            value: https://github.com/Bashayr29/GoHiBeesh.git
    - name: image
      resourceSpec:
        type: image
        params:
          - name: url
            value: image-registry.openshift-image-registry.svc:5000/workshops/go-hi-beesh-git:latest

  
